spring:
  application:
    name: fluxo
  datasource:
    url: jdbc:postgresql://localhost:5432/fluxo
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

jwt:
  secret: ${JWT_SECRET:d7c189b8822556b26b3bfdf8d27038e219fbcfb93eaee89b9a67bc647db2de74}