spring:
  application:
    name: fluxo
  datasource:
    url: jdbc:postgresql://localhost:5432/fluxo
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

jwt:
  secret: ${JWT_SECRET}